version: '3'

networks:
  hadoop:
    driver: bridge

services:
  hadoop-master:
    image: lingatsu/tp-final-bigdata:latest
    container_name: hadoop-master
    hostname: hadoop-master
    networks:
      - hadoop
    ports:
      - "9870:9870"
      - "8088:8088"
      - "7077:7077"
      - "16010:16010"
      - "9999:9999"
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
      - HADOOP_HOME=/usr/local/hadoop
    volumes:
      - ./hdfs-input:/root/hdfs-input
      - ./TP_Final:/root/scripts
    tty: true
    stdin_open: true

  hadoop-slave1:
    image: lingatsu/tp-final-bigdata:latest
    container_name: hadoop-slave1
    hostname: hadoop-slave1
    networks:
      - hadoop
    ports:
      - "8040:8042"
    tty: true
    stdin_open: true

  hadoop-slave2:
    image: lingatsu/tp-final-bigdata:latest
    container_name: hadoop-slave2
    hostname: hadoop-slave2
    networks:
      - hadoop
    ports:
      - "8041:8042"
    tty: true
    stdin_open: true
